Repository dhruvpatidar359/nextdraw, pull requests merged in 2024-05, with the labels that each got.

#41 added panning option using mouse click and space key
  components/Canvas.jsx
Labels: gssoc, level2

#34 Fill style option implemented for elements
  components/PropertiesBar/PropertiesBar.jsx
Labels: gssoc, level3

#46 PR 41 broke the functionality, here's a fix to it
  components/Canvas.jsx
Labels: gssoc, level2

#58 added font style and font weight to text tool
  components/Canvas.jsx
  components/Drawing/Drawing.js
  components/ElementManipulation/Element.js
  components/PropertiesBar/PropertiesBar.jsx
  components/Redux/GlobalProps.js
  export/export.js
Labels: gssoc, level2

#67 Adding enhanced_readme
  README.md
Labels: gssoc, level1
